sudo: false
before_install:
  - npm install -g node-gyp
  - npm install -g node-sass
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
language: node_js
node_js:
  - "stable"

install:
  - npm install

script:
  - npm run lint
  - npm run unit